sudo: false
language: node_js
python:
  - '2.7'
os:
  - linux
  - osx
node_js:
  - '0.12'
  - '4.1'
  - '4.2'
services:
  - mongodb
  - redis
before_script:
  - python --version
  - npm install -g node-gyp
  - npm install -g babel
  - npm install -g pm2
  - npm install
script:
  - npm start
