sudo: true
language: cpp
os:
  - linux
  - osx
env:
  - NODE_VERSION='0.12'
  - NODE_VERSION='4.0'
  - NODE_VERSION='4.1'
  - NODE_VERSION='4.2'
  - NODE_VERSION='5.0'
  - NODE_VERSION='5.1'
  - NODE_VERSION='5.2'
  - NODE_VERSION='5.3'
  - NODE_VERSION='5.4'
python:
  - '2.7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
  - redis
matrix:
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
  - source /tmp/.nvm/nvm.sh;
  - nvm install $NODE_VERSION;
  - nvm use --delete-prefix $NODE_VERSION;
install:
  - npm install -g node-gyp
  - npm install -g babel
  - npm install -g pm2
  - npm install
script:
  - npm start
