sudo: true
language: node_js
python:
  - '2.7'
os:
  - linux
node_js:
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '5.1'
  - '5.2'
  - '5.3'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
  - redis
before_script:
  - npm install -g node-gyp
  - npm install -g babel
  - npm install -g pm2
  - npm install
script:
  - npm start
